### ISSUE TITLE
sentinel policy link broken in rendered documentation in registry

### ISSUE THREAD

**Issue by quixoticmonk** [hashicorp/policy-library-CIS-Policy-Set-for-AWS-EC2-Terraform#12]
# Description

The sentinel policy links are set to relative paths in the GitHub repos which break on registry.

- Policy : Ensure that EC2 Metadata Service only allows IMDSv2
- link : https://registry.terraform.io/policies/hashicorp/CIS-Policy-Set-for-AWS-EC2-Terraform/policies/ec2-metadata-imdsv2-required.sentinel
- Reference : https://github.com/hashicorp/policy-library-CIS-Policy-Set-for-AWS-EC2-Terraform/blob/main/docs/policies/ec2-metadata-imdsv2-required.md#description

I can open a PR to fix these links to be absolute ones if that is a feasible solution for all these.

**Comment by harinimhc** [comment]
Hey there! Thank you submitting the ticket, we are currently working on this.

**Comment by harinimhc** [comment]
This has been fixed.
